apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: 2018-09-11T17:44:31Z
  labels:
    app: mcap
  name: mcap
  namespace: gcpe-mygovbc-msp-tools
  resourceVersion: "2270443313"
  selfLink: /apis/build.openshift.io/v1/namespaces/gcpe-mygovbc-msp-tools/buildconfigs/mcap
  uid: 56e198a4-b5ea-11e8-8803-0050568379a2
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: mcap:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/bcgov/sbc-mcap.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  triggers:
  - imageChange:
      lastTriggeredImageID: docker-registry.default.svc:5000/openshift/nodejs@sha256:91002d434b585df0262f0350fe91dac9adb3e56d6b9ccfea47ac91064f4513b7
    type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 52
