name: genesys build
on:
  push:
    paths:
      - "genesys/src/**/*.js"
      - "genesys/src/**/*.html"
      - "genesys/src/**/*.css"
      - "genesys/package*.json"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./genesys
jobs:
  s2i-build:
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # needs: [test, build]
    steps:
      - name: S2I Build
        env:
          NAMESPACE: 3a0694-tools
          BUILD_NAME: genesys-main-build
          IMAGE_NAME: genesys
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL}}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            'version'
            'start-build ${BUILD_NAME} -n ${NAMESPACE} --follow'
            'tag -n ${NAMESPACE} ${NAMESPACE}/${IMAGE_NAME}:latest ${NAMESPACE}/${IMAGE_NAME}:dev'
